// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCecwkZafzAQCOsDbsgTqY4e6BOoMP5axA',
    appId: '1:394142732292:web:a8425a347599e5d22fe551',
    messagingSenderId: '394142732292',
    projectId: 'trash-to-treasure-76528',
    authDomain: 'trash-to-treasure-76528.firebaseapp.com',
    storageBucket: 'trash-to-treasure-76528.firebasestorage.app',
    measurementId: 'G-VZXKDYK0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKyIi38q2NSJdOiok2h4LYm9EYrq8VJA',
    appId: '1:394142732292:android:57390736955d70df2fe551',
    messagingSenderId: '394142732292',
    projectId: 'trash-to-treasure-76528',
    storageBucket: 'trash-to-treasure-76528.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVx-fyEIqNzIhb6w21OJtRNo4rRm8juHM',
    appId: '1:394142732292:ios:4ff876ca4328c6c52fe551',
    messagingSenderId: '394142732292',
    projectId: 'trash-to-treasure-76528',
    storageBucket: 'trash-to-treasure-76528.firebasestorage.app',
    iosBundleId: 'com.example.t2tAdmin',
  );
}
